
####
####
# testing EGFR as a biomarker for Erlotinib (This is used to compare to the rules generated by our method for Erlotinib)

drug <- "Erlotinib"
gene <- "EGFR"

names(gene) <- rownames(fData(CCLE@molecularProfiles$rnaseq))[which(fData(CCLE@molecularProfiles$rnaseq)[,"gene_name"]==gene)]

gene_data <- ccleRnaSeq[,names(gene)]

drug_data <- AAC_CTRPv2[drug,]
drug_data <- drug_data[!is.na(drug_data)]

common <- intersect(names(drug_data),names(gene_data))

r1 <- paired.concordance.index.weighted.version(gene_data[common],drug_data[common],delta.obs = 0.2)$cindex


require(caret)
flds <- createFolds(common, k = 5, list = TRUE, returnTrain = FALSE)
names(flds)[1] <- "train"

results <- unlist(lapply(1:5, function(x){

  train <- common[-flds[[x]]]
  test <- common[flds[[x]]]
  data <- data.frame("gene"=gene_data[train],"drug"=drug_data[train],stringsAsFactors=F)
  data_test <- data.frame("gene"=gene_data[test],stringsAsFactors=F)
  model <- lm(formula = drug~gene,data)
  predict(object = model, newdata = data_test)
  }))

r_cv <- paired.concordance.index.weighted.version(results,drug_data[names(results)],delta.obs = 0.2)$cindex


r1
r_cv

#############################
#############################
#############################

possibleMarkers_3 <- read.csv("data/Table S1.csv",sep = "\t",header = T,stringsAsFactors = F)

possibleMarkersfinal <- possibleMarkers_3[,c("compound","gene")]

drugs <- unique(possibleMarkersfinal$compound)
drugs <- intersect(drugs,rownames(AAC_CTRPv2))

results_final <- lapply(drugs, function(drug){
  print("###########################")
  print(drug)
  genes <- possibleMarkersfinal[possibleMarkersfinal$compound==drug,"gene"]
  results <- lapply(genes, function(gene){
    print(gene)
    ibx <- which(fData(CCLE@molecularProfiles$rnaseq)[,"gene_name"]==gene)
    if(length(ibx)==0)
      return(NA)
    if(length(ibx)>1)
      ibx <- ibx[1]
    names(gene) <- rownames(fData(CCLE@molecularProfiles$rnaseq))[ibx]
    
    gene_data <- ccleRnaSeq[,names(gene)]
    
    drug_data <- AAC_CTRPv2[drug,]
    drug_data <- drug_data[!is.na(drug_data)]
    
    common <- intersect(names(drug_data),names(gene_data))
    
    r1 <- paired.concordance.index.weighted.version(gene_data[common],drug_data[common],delta.obs = 0.2)$cindex
    if(r1 < 0.5) 
      1-r1
    else
      r1
  })
  names(results) <- genes
  return(unlist(results))
  
})

names(results_final) <- drugs
boxplot(results_final)

library(reshape2)
result <- melt(results_final)
colnames(result) <- c('CI','Drug')

result <- data.frame(stringsAsFactors = F,check.names = F)

result <- lapply(results_final, function(x){
  return(data.frame("gene"=names(x),"CI"=x,stringsAsFactors = F))
})

result <- melt(result)
result <- result[,-2]
colnames(result) <- c('gene','CI','Drug')

library(ggrepel)

pdf("plots/FigS5.pdf",width = 11,height = 5)
ggplot(result,mapping = aes(x=Drug,y=CI))+
  geom_boxplot(outlier.shape = NA,fill="lightgrey") +
  geom_point(position = "jitter",mapping = aes(color=(!is.na(CI) & CI>0.6))) +
  scale_colour_manual(name = 'CI > 0.6', values = setNames(c('red','black'),c(T, F))) +
  ggtitle("Evaluation of curated known biomarkers") +
  geom_text_repel(data = result[result$CI>0.6,],mapping = aes(label=gene),color="red") +
  theme_bw() + theme(plot.title = element_text(hjust=0.5),text = element_text(size = 10,face = "bold")
                     ,axis.line = element_line(colour = "black"),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     #                  panel.border = element_blank(),
                     panel.background = element_blank())
  
  
  
mean(result$CI,na.rm=T)
dev.off()




